# Generated by Django 2.2.7 on 2019-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcrudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
